language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install -e ."

script:
  - "python -m compileall -f ."
  - "python setup.py develop"
  - "python setup.py test"
  - "py.test"

notifications:
  email:
    on_success: change
    on_failure: always
